development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://bdtvmywlryooez:7a7cd6c3aef405caf0450af8e711e3d28411edfa6a32da11a797f8907e905887@ec2-54-204-46-60.compute-1.amazonaws.com:5432/d8n45phg6tdcra
  channel_prefix: nameofapp_production
